version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB="n_buy_db"
      - POSTGRES_USER="Cesar"
      - POSTGRES_PASSWORD="Dragones123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  Server:
    build: .
    command: python manage.py runserver 0.0.0.0:3201
    volumes:
      - .:/app
    ports:
      - "3201:3201"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_NAME=n_buy_db
      - DB_USER=Cesar
      - DB_PASSWORD=Dragones123
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
